# Generated by Django 2.2 on 2020-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
