# Generated by Django 3.2.7 on 2023-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210911_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, default='Published', max_length=50, null=True),
        ),
    ]
