# Generated by Django 3.2.7 on 2023-04-25 04:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillFeeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('partial_amount', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'parents',
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('admitted_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='YearGradeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('year_ad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'year_grade_section',
                'unique_together': {('year', 'grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='YearGradeSectionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('year_grade_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.yeargradesection')),
            ],
            options={
                'verbose_name': 'year_grade_section_students',
                'db_table': 'year_grade_section_students',
                'unique_together': {('year_grade_section', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('relationship', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'student_parents',
                'db_table': 'student_parents',
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, through='student.StudentParent', to='student.Parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='year_grade_section',
            field=models.ManyToManyField(blank=True, through='student.YearGradeSectionStudent', to='student.YearGradeSection'),
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.billmodel')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='FeeTypeModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('STUDENT_FEES', 'Student Fees'), ('ADMISSION_FEE', 'Admission Fee'), ('EXAM_FEE', 'Exam Fee'), ('UNIFORM_FEE', 'Uniform Fee'), ('OTHER_FEE', 'Other Fee')], max_length=20)),
                ('amount', models.FloatField()),
                ('bills', models.ManyToManyField(through='student.BillFeeTypeModel', to='student.BillModel')),
            ],
            options={
                'db_table': 'fee_type',
            },
        ),
        migrations.AddField(
            model_name='billmodel',
            name='fee_types',
            field=models.ManyToManyField(through='student.BillFeeTypeModel', to='student.FeeTypeModel'),
        ),
        migrations.AddField(
            model_name='billfeetypemodel',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.billmodel'),
        ),
        migrations.AddField(
            model_name='billfeetypemodel',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.feetypemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='billfeetypemodel',
            unique_together={('left', 'right')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('year_grade_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.yeargradesection')),
            ],
            options={
                'db_table': 'attendances',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
