# Generated by Django 3.2.7 on 2023-04-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parent'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_grade_section',
        ),
        migrations.AddField(
            model_name='student',
            name='year_grade_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.yeargradesection'),
        ),
    ]
