# Generated by Django 3.2.7 on 2023-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_parents',
            new_name='student_parent',
        ),
    ]
