# Generated by Django 3.2.7 on 2023-04-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230425_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parents',
            new_name='parent',
        ),
    ]
