# Generated by Django 3.2.7 on 2023-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230408_0321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentYearModel',
            new_name='YearStudentModel',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='year',
            field=models.ManyToManyField(blank=True, through='student.YearStudentModel', to='student.YearModel'),
        ),
        migrations.AlterModelTable(
            name='gradesectionmodel',
            table='grade_sections',
        ),
        migrations.AlterModelTable(
            name='studentparentmodel',
            table='student_parents',
        ),
        migrations.AlterModelTable(
            name='yeargrademodel',
            table='year_grades',
        ),
        migrations.AlterModelTable(
            name='yeargradesectionmodel',
            table='year_grade_sections',
        ),
        migrations.AlterModelTable(
            name='yeargradesectionstudentmodel',
            table='year_grade_section_students',
        ),
        migrations.AlterModelTable(
            name='yeargradestudentmodel',
            table='year_grade_students',
        ),
        migrations.AlterModelTable(
            name='yearstudentmodel',
            table='year_students',
        ),
    ]
