# Generated by Django 3.2.7 on 2023-05-14 13:48

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230514_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestudent',
            name='fee_date',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-1-12'),
            preserve_default=False,
        ),
    ]
