# Generated by Django 3.2.7 on 2023-04-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_parents_studentmodel_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentparentmodel'),
        ),
    ]
