# Generated by Django 3.2.7 on 2023-05-14 13:49

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_feestudent_fee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestudent',
            name='fee_date',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-01-31'),
        ),
    ]
