# Generated by Django 3.2.7 on 2023-04-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentmodel_student_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='parent',
            new_name='parents',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_parent',
        ),
    ]
