# Generated by Django 3.2.7 on 2023-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230408_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billfeetypemodel',
            old_name='bill',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='billfeetypemodel',
            old_name='fee_type',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='gradesectionmodel',
            old_name='grade',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='gradesectionmodel',
            old_name='section',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='studentparentmodel',
            old_name='student',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='studentparentmodel',
            old_name='parent',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='yeargrademodel',
            old_name='year',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='yeargrademodel',
            old_name='grade',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='yeargradesectionmodel',
            old_name='year_grade',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='yeargradesectionmodel',
            old_name='section',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='yeargradesectionstudentmodel',
            old_name='year_grade_section',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='yeargradesectionstudentmodel',
            old_name='student',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='yeargradestudentmodel',
            old_name='year_grade',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='yeargradestudentmodel',
            old_name='student',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='yearstudentmodel',
            old_name='year',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='yearstudentmodel',
            old_name='student',
            new_name='right',
        ),
        migrations.AddField(
            model_name='studentparentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentparentmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentparentmodel',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grademodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yearmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='billfeetypemodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='gradesectionmodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='studentparentmodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargrademodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradesectionmodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradesectionstudentmodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradestudentmodel',
            unique_together={('left', 'right')},
        ),
        migrations.AlterUniqueTogether(
            name='yearstudentmodel',
            unique_together={('left', 'right')},
        ),
    ]
