# Generated by Django 3.2.7 on 2023-04-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_parents_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
    ]
