# Generated by Django 3.2.7 on 2023-04-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20230408_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesectionmodel',
            old_name='left',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='gradesectionmodel',
            old_name='right',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='studentparentmodel',
            old_name='right',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='studentparentmodel',
            old_name='left',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='yeargrademodel',
            old_name='right',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='yeargrademodel',
            old_name='left',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='yeargradesectionmodel',
            old_name='right',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='yeargradesectionmodel',
            old_name='left',
            new_name='year_grade',
        ),
        migrations.RenameField(
            model_name='yeargradesectionstudentmodel',
            old_name='right',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='yeargradesectionstudentmodel',
            old_name='left',
            new_name='year_grade_section',
        ),
        migrations.RenameField(
            model_name='yeargradestudentmodel',
            old_name='right',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='yeargradestudentmodel',
            old_name='left',
            new_name='year_grade',
        ),
        migrations.RenameField(
            model_name='yearstudentmodel',
            old_name='right',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='yearstudentmodel',
            old_name='left',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='gradesectionmodel',
            unique_together={('grade', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='studentparentmodel',
            unique_together={('student', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargrademodel',
            unique_together={('year', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradesectionmodel',
            unique_together={('year_grade', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradesectionstudentmodel',
            unique_together={('year_grade_section', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='yeargradestudentmodel',
            unique_together={('year_grade', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='yearstudentmodel',
            unique_together={('year', 'student')},
        ),
    ]
