# Generated by Django 3.2.7 on 2023-05-16 10:14

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_feestudent_fee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admitted_on_bs',
        ),
        migrations.AlterField(
            model_name='feestudent',
            name='fee_date',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-02-02'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admitted_on',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-02-02'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob_bs',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
