# Generated by Django 3.2.7 on 2023-05-16 10:17

from django.db import migrations, models
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230516_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_on_bs',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-02-02'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admitted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
