# Generated by Django 3.2.7 on 2023-04-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230425_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='billfeetypemodel',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='billmodel',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='studentparent',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='yeargradesection',
            old_name='status',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='yeargradesectionstudent',
            old_name='status',
            new_name='active',
        ),
    ]
