# Generated by Django 3.2.7 on 2023-05-31 13:06

from django.db import migrations, models
import django.db.models.deletion
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230516_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='fee',
        ),
        migrations.AddField(
            model_name='bill',
            name='student_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentparent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='fee_student',
        ),
        migrations.AddField(
            model_name='bill',
            name='fee_student',
            field=models.ManyToManyField(to='student.FeeStudent'),
        ),
        migrations.AlterField(
            model_name='feestudent',
            name='fee_date',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-02-17'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admitted_on_bs',
            field=nepali_datetime_field.models.NepaliDateField(default='2080-02-17'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'dob_bs')},
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='receipt/images/')),
                ('paid_by', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=500)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.bill')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
