# Generated by Django 3.2.7 on 2023-04-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20230425_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob_bs',
            field=models.DateField(blank=True, null=True),
        ),
    ]
