# Generated by Django 3.2.7 on 2023-04-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_dob_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admitted_on_bs',
            field=models.DateField(blank=True, null=True),
        ),
    ]
