# Generated by Django 3.2.7 on 2023-05-06 04:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_admitted_on_bs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('fee_type', models.CharField(choices=[('Admission Fee', 'Admission Fee'), ('Monthly Fee', 'Monthly Fee'), ('Exam Fee', 'Exam Fee'), ('Sarashwati Puja', 'Sarashwati Puja'), ('Tie Long', 'Tie Long'), ('Tie Short', 'Tie Short')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('year_grade_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.yeargradesection')),
            ],
            options={
                'db_table': 'fees',
            },
        ),
        migrations.CreateModel(
            name='FeeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'fee_students',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('due_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Void', 'Void'), ('Paid', 'Paid')], max_length=30)),
                ('fee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.fee')),
                ('fee_student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.feestudent')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
